[package]
name = "test_macroquad"
version = "0.1.0"
authors = ["Adi-df <adidf-web@laposte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.5.2"
macroquad = "0.3"